In [2]:
import numpy as np
import time
print("imported numpy libraries")

imported numpy libraries


In [3]:
a=np.random.rand(1000000000)


In [5]:
a

array([0.65834346, 0.74159126, 0.11559781, ..., 0.55413503, 0.12076221,
       0.53242555])

In [6]:
#list 

start =time.time()
mean_list=sum(a)/len(a)
print(time.time()-start)

116.29736948013306


In [9]:
# numpy 

start =time.time()
mean_np=np.mean(a)
print(time.time()-start)

27.359089136123657


In [10]:
mean_list


0.499999540092543

In [11]:
mean_np

0.499999540092543

In [15]:
# what version i use numpy

np.__version__

'1.24.3'

In [14]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


## operation

In [17]:
#arr=np.array()   --> syntax

In [18]:
#0D Zero Dimensional 
arr=np.array(4)

In [19]:
arr

array(4)

In [20]:
#1D= ARRAY
ARR=np.array([1,2,3,4,5,6,9,10])

In [21]:
ARR


array([ 1,  2,  3,  4,  5,  6,  9, 10])

In [22]:
#2D ARRAY
arr2=np.array([[1,2,3],[3,4,5],[6,7,8]])

In [23]:
arr2

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
#3D Array
arr3=np.array([[[1,2,3,4],
               [5,4,6,7]]
               ,[[1,2,3,4],
                [4,54,6,7]]])

In [34]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  4,  6,  7]],

       [[ 1,  2,  3,  4],
        [ 4, 54,  6,  7]]])

In [27]:
arr4=np.array((1,2,3,4,5))

In [28]:
type(arr)

numpy.ndarray

#  ndim attribute - It will gonna return the deminsion of array

In [29]:
arr.ndim

0

In [30]:
ARR.ndim

1

In [31]:
arr2.ndim

2

In [35]:
arr3.ndim

3

# i want to convert 1D array in 10 demensional array

In [36]:
arr1=np.array([1,2,3,4,5],ndmin=10)

In [37]:
arr1.ndim

10

In [38]:
arr1

array([[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]])

# shape - it tells about the size of the array

In [40]:
arr2.shape   #--> it specify the rows and columns of array

(3, 3)

In [41]:
arr3.shape  #--> how many 2d array do you have 2,no. of rows-2,no. of column-4

(2, 2, 4)

In [42]:
arr3=np.array([[[1,2,3,4],
               [5,4,6,7]]
               ,[[1,2,3,4],
                [4,54,6,7]]],ndmin=10)

In [43]:
arr3.shape   #--> how many 10d array do you have 1, and so on 

(1, 1, 1, 1, 1, 1, 1, 2, 2, 4)

# dtype - it tell about the type of the data 

In [45]:
ARR.dtype

dtype('int32')

In [46]:
arr2.dtype

dtype('int32')

In [49]:
arr5=np.array(["apple","mangoes","cherry",9.9])

In [50]:
arr5.dtype

dtype('<U32')

In [51]:
arr5

array(['apple', 'mangoes', 'cherry', '9.9'], dtype='<U32')

In [53]:
arr2=np.array([[1,2,3],[3,4,5],[6,7,8]],dtype='int64')

In [54]:
arr2.dtype

dtype('int64')

In [56]:
arr2.dtype #--> space allocate to array  

dtype('int16')

# size - total number of the element in an array

In [57]:
arr2.size

9

In [58]:
arr2

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

# --syntax    np.size(ndarraym,1(row),0(column))   #--> it uses this concept in index slicing 

In [59]:
np.size(arr2,0)     #-->it specify the no. of elements in columns

3

In [60]:
np.size(arr2,1)   ##-->it specify the no. of elements in rows

3

# itemsize  -it tells us about the length of the single element of array in bytes

In [63]:
arr2.itemsize   # --> "2" bytes given the each of the element in array [1,2,3],[3,4,5],[6,7,8]

2

# nbytes  -total bytes occupied by array 's elements 

In [64]:
arr2.nbytes

18

In [3]:
arr2=np.array([['1',2,3],[3,4,5],[6,7,8]])  #--> # --> "2" bytes given the each of the element in array

In [4]:
arr2.itemsize

44

In [67]:
arr2.nbytes

396