#  CRUD OPERATION 

In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],[4,5,6]])

In [4]:
arr.ndim

2

In [5]:
#np.zeros()
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr=np.zeros((3,3))  # 2D array shape -> no. of rows and no. of columns

In [7]:
arr


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr1=np.zeros(10)  # 1D  array

In [9]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr2.np.zeros([10,10])   # provide argument [list]and (tuple)

In [10]:
arr=np.zeros([10,3,4])

In [11]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
#np.ones()
arr=np.ones([10])

In [15]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
#np.empty()

arr1=np.empty([3,4])

In [22]:
arr1

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        7.56587584e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.24611538e-306],
       [6.23054293e-307, 1.95821982e-306, 1.42410974e-306,
        1.42410974e-306]])

In [27]:
arr2=np.empty([2,2])

In [28]:
arr2

array([[2.12199579e-314, 1.38990724e-311],
       [4.88136858e-321, 6.95208344e-310]])

In [31]:
arr=np.full([3,4,4],5)

In [32]:
arr

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [33]:
# identity matrix -all princepal diagonal should zero rest will be zero.
# no. of row is equal to no. of column

arr=np.eye(9)  #eye([9,9])

In [34]:
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
arr=np.diag([1,2,3,4,5,6,7])

In [36]:
arr

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [39]:
#np.linspace(10,100,10)

arr=np.linspace(1,10,20)

In [40]:
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [43]:
arr=np.random.randint(15,25,size=(2,3))

In [44]:
arr

array([[21, 21, 16],
       [22, 19, 17]])

In [48]:
# np.arange()

arr=np.arange(1,12,2)

In [49]:
arr

array([ 1,  3,  5,  7,  9, 11])

#  Update 

In [64]:
arr1=np.array([1,2,3,4,5])
arr2 =np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arr3 =np.array([[
    [1,2,3,4],
    [5,6,7,8]
     ]
    ,[[1,3,5,7],
    [8,9,10,12]]
])

In [65]:
arr3.ndim

3

In [59]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [62]:
#indexing 

#1D array 
arr1[-1]
arr1[4]

#2D array

arr2[1][2]
arr2[2,2]

5

In [67]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 1,  3,  5,  7],
        [ 8,  9, 10, 12]]])

In [68]:
arr3[0,1,1] =23  # 6 replace with 23

In [69]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5, 23,  7,  8]],

       [[ 1,  3,  5,  7],
        [ 8,  9, 10, 12]]])

# slicing   -> only you think about row 


In [71]:
arr2[1:2]    # row 1 -> inclusive and row 2 -> exclusive

array([[5, 6, 7, 8]])

In [72]:
arr3[0:1]

array([[[ 1,  2,  3,  4],
        [ 5, 23,  7,  8]]])

In [76]:
arr3[0,1:]    # arr3[0,1]

array([[ 5, 23,  7,  8]])

In [79]:
arr3[0,1,0:2]

array([ 5, 23])

In [80]:
arr3[0,1][0:2]

array([ 5, 23])

In [82]:
arr3[0,1,[0:2]]

SyntaxError: invalid syntax (4019501843.py, line 1)

In [ ]:
# Quiz


#create a matrix 3x4 , 10 to 500

In [83]:
arr4=np.linspace(10,500,12)

In [84]:
arr4

array([ 10.        ,  54.54545455,  99.09090909, 143.63636364,
       188.18181818, 232.72727273, 277.27272727, 321.81818182,
       366.36363636, 410.90909091, 455.45454545, 500.        ])

In [85]:
arr4.reshape(3,4)

array([[ 10.        ,  54.54545455,  99.09090909, 143.63636364],
       [188.18181818, 232.72727273, 277.27272727, 321.81818182],
       [366.36363636, 410.90909091, 455.45454545, 500.        ]])

In [86]:
arr4.reshape(12,1)

array([[ 10.        ],
       [ 54.54545455],
       [ 99.09090909],
       [143.63636364],
       [188.18181818],
       [232.72727273],
       [277.27272727],
       [321.81818182],
       [366.36363636],
       [410.90909091],
       [455.45454545],
       [500.        ]])

In [87]:
arr4.reshape(2,3,2)

array([[[ 10.        ,  54.54545455],
        [ 99.09090909, 143.63636364],
        [188.18181818, 232.72727273]],

       [[277.27272727, 321.81818182],
        [366.36363636, 410.90909091],
        [455.45454545, 500.        ]]])

In [ ]:
# create a 7*9 matrix where allthe elements are random

In [88]:
arr=np.random.randint(1,15,size=(7,9))

In [89]:
arr

array([[10, 13,  2, 14, 14,  8,  1, 11,  5],
       [14,  9,  6, 11,  9, 11,  5, 14,  8],
       [14,  8,  1, 14,  9, 11, 12,  5,  5],
       [ 1,  9,  9,  6,  1,  9, 14, 12,  7],
       [ 9, 10,  8, 11,  1,  6,  6, 12,  7],
       [ 3, 10,  7, 13,  1, 10,  1,  5,  5],
       [ 7, 10, 14,  5,  1, 13, 13,  7,  5]])

In [90]:
arr=np.random.rand(63).reshape(7,9)

In [91]:
arr


array([[0.62178397, 0.2140841 , 0.27882203, 0.73004131, 0.2086905 ,
        0.2629794 , 0.19310981, 0.76377743, 0.02614771],
       [0.41919493, 0.08729019, 0.10430495, 0.52758876, 0.93308498,
        0.73125098, 0.12048553, 0.15047007, 0.39293846],
       [0.01506562, 0.95858087, 0.87886286, 0.60029561, 0.87752954,
        0.92734656, 0.81675196, 0.1976763 , 0.90342784],
       [0.27921554, 0.49668774, 0.40487392, 0.24883584, 0.26985505,
        0.11935769, 0.99926441, 0.39530311, 0.57931227],
       [0.73064784, 0.08089301, 0.30466339, 0.73795897, 0.1326606 ,
        0.62189835, 0.24125481, 0.17835785, 0.07120376],
       [0.52814992, 0.59418388, 0.61070495, 0.24256557, 0.04900772,
        0.14627135, 0.98365568, 0.9928747 , 0.29257095],
       [0.51749129, 0.91302114, 0.27003798, 0.04823677, 0.88717073,
        0.92000218, 0.02423931, 0.73716571, 0.14238326]])

In [92]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [2]:
arr2d=np.array([15,16,17,18])
arr2dd=np.array([15,16,17,18])

In [3]:
np.append(arr2d,arr2dd) 

array([15, 16, 17, 18, 15, 16, 17, 18])

In [4]:
arrop =np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arrpo =np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])

In [106]:
np.append(arrop,arrpo,axis=0)    # dimensional is same 

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [108]:
arrop+arrpo    # add the corresponding element 

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 2,  6, 10, 14]])

In [109]:
list1=[1,2,3]
list2=[1,1,1]
list1+list2    # this will concatenate list1 and list2

[1, 2, 3, 1, 1, 1]

In [110]:
arrop+10     # each element of array add 10 value      

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [11, 13, 15, 17]])

In [111]:
arrop *10   # all element is multiply by 10 

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [10, 30, 50, 70]])

In [112]:
arrop/10

array([[0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8],
       [0.1, 0.3, 0.5, 0.7]])

In [113]:
arrop **2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64],
       [ 1,  9, 25, 49]])

In [114]:
arrop-2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [-1,  1,  3,  5]])

In [115]:
arrop * arrpo   # it will be cross multi

# 2type - cross and dot multiplecation 

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64],
       [ 1,  9, 25, 49]])