In [1]:
list1=[10,20,30,40,50]
list2=[10,20,30,40,50]
print(list1==list2)
print(list1 is list2)

True
False


In [4]:
import numpy as np


In [5]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[11,12,13],[14,15,16]])

In [12]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

# Stacking


In [4]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2

array([[11, 12, 13],
       [14, 15, 16]])

In [7]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [8]:
np.vstack((arr1,arr2,arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [11]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [19]:
arr3=np.array((100,200,300))

In [20]:
np.vstack((arr1,arr3))  # both array having same column

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [21]:
np.hstack((arr1,arr3)) # both you need both array having same row

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

dstack()

In [23]:
np.dstack((arr1,arr2,arr1))

array([[[ 1, 11,  1],
        [ 2, 12,  2],
        [ 3, 13,  3]],

       [[ 4, 14,  4],
        [ 5, 15,  5],
        [ 6, 16,  6]]])

 spliting

In [28]:
#array_split()

br=np.array_split(arr3,4)

In [27]:
br[1]

array([200])

In [29]:
br[3]

array([], dtype=int32)

In [30]:
#array_split()

br=np.array_split(arr3,2)

In [31]:
br

[array([100, 200]), array([300])]

In [32]:
#array_split()

br=np.array_split(arr3,10)

In [33]:
br

[array([100]),
 array([200]),
 array([300]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

Seaching

In [34]:
newarr=np.array((1,2,3,4,5,4,4))

In [35]:
newarr

array([1, 2, 3, 4, 5, 4, 4])

In [37]:
#where 

np.where(newarr==4)

(array([3, 5, 6], dtype=int64),)

In [40]:

np.where(newarr>4)   # return all indexes those elements that satisfy the condition 

(array([4], dtype=int64),)

In [39]:
#where 

np.where(newarr<4)

(array([0, 1, 2], dtype=int64),)

sorting

In [42]:
newarr=np.array((10,5,6,-10,-7,20,0,4,4.5,18))

In [43]:
newarr

array([ 10. ,   5. ,   6. , -10. ,  -7. ,  20. ,   0. ,   4. ,   4.5,
        18. ])

In [44]:
np.sort(newarr)   # ascending

array([-10. ,  -7. ,   0. ,   4. ,   4.5,   5. ,   6. ,  10. ,  18. ,
        20. ])

In [46]:
arr4=np.array([[1,9,3],[4,15,6]])
np.sort(arr4)

array([[ 1,  3,  9],
       [ 4,  6, 15]])

In [47]:
np.where(arr4==6)

(array([1], dtype=int64), array([2], dtype=int64))

In [49]:
-np.sort(-newarr)  #descending

array([ 20. ,  18. ,  10. ,   6. ,   5. ,   4.5,   4. ,   0. ,  -7. ,
       -10. ])

In [50]:
np.sort(-newarr)   # it is not working

array([-20. , -18. , -10. ,  -6. ,  -5. ,  -4.5,  -4. ,  -0. ,   7. ,
        10. ])

any(),all()

In [60]:
newarr=np.array([2,4,6,8,9])

In [61]:
np.any(newarr%2==0)

True

In [62]:
np.all(newarr%2==0)

False

In [63]:
a=np.arange(12)

In [64]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
np.reshape(a,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

resize()

In [67]:
np.resize(a,(3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [68]:
np.resize(a,(10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11,  0,  1],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3]])

Delete 

In [69]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [76]:
delmat=np.array([[1,2,3],[4,3,5]])

In [77]:
np.delete(delmat,3)

array([1, 2, 3, 3, 5])

In [81]:
np.delete(delmat,2,axis=1)   # it delete which value having rowwise index value is 2 of the matrix

array([[1, 2],
       [4, 3]])

In [80]:
np.delete(delmat,1,axis=0)  # it delete which value having columnwie index value is 1 of the matrix

array([[1, 2, 3]])

In [93]:
delmat

array([[1, 2, 3],
       [4, 3, 5]])

In [94]:
np.delete(delmat,1,axis=1)  

array([[1, 3],
       [4, 5]])

LCM

In [90]:
num1=25
num2=125
num3=625
np.lcm([num1,num2,num3])

TypeError: lcm() takes from 2 to 3 positional arguments but 1 were given

In [91]:
num1=25
num2=125
num3=625
np.lcm.reduce([num1,num2,num3])

625

In [86]:
newarr

array([2, 4, 6, 8, 9])

In [87]:
np.lcm(newarr)

TypeError: lcm() takes from 2 to 3 positional arguments but 1 were given

In [88]:
np.lcm.reduce(newarr)

72

GCD-> Greatest common divisor

In [95]:
a=6
b=9

#gcd()
np.gcd(a,b)

3

In [96]:
np.gcd.reduce(newarr)

1

In [98]:
newarr=np.array([2,4,6,8,10])

In [99]:
np.gcd.reduce(newarr)

2

# 3x+4y=90 ,9x+6y=10 linear equation

In [101]:
#3x+y=9
#x+2y=8

a=np.array([[3,1],[1,2]])
b=np.array([9,8])

In [102]:
np.linalg.solve(a,b)

array([2., 3.])

Quadratic equation

In [103]:
# x^2+4x = -4
# x^2+4x+4=0

coeff=np.array([1,4,4])

In [105]:
# roots

np.roots(coeff)

array([-2.+1.3377935e-08j, -2.-1.3377935e-08j])

In [106]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[40,50,60]])

In [107]:
np.vdot(a,b)

910

In [108]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.mean(a)

3.5

 weighted mean

In [110]:
array=np.array([1,2,3,4])
weight=np.array([4,3,2,1])

In [111]:
np.average(array,weights=weight)

2.0

In [112]:
array=np.array([-10,0.3,1.5,19,-50,-3.5,11.5,9])

In [113]:
array

array([-10. ,   0.3,   1.5,  19. , -50. ,  -3.5,  11.5,   9. ])

In [115]:
np.sort(array)

array([-50. , -10. ,  -3.5,   0.3,   1.5,   9. ,  11.5,  19. ])

argsort()

In [116]:
np.argsort(array)

array([4, 0, 5, 1, 2, 7, 6, 3], dtype=int64)

In [117]:
array**2

array([1.0000e+02, 9.0000e-02, 2.2500e+00, 3.6100e+02, 2.5000e+03,
       1.2250e+01, 1.3225e+02, 8.1000e+01])

In [119]:
np.sqrt(newarr)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [122]:
np.square(newarr)

array([  4,  16,  36,  64, 100])