In [2]:
import numpy as np

In [3]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[10,9,8,7,6],[5,4,3,2,1]])

# mathematical functional & stats

In [6]:
#Addiing two matrices
arr1 +arr2

# Adding an element 
arr1+20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr3=np.array([1,2,3,4,5])

In [10]:
arr1+arr3

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [11]:
# substraction 

In [12]:
arr1 -arr2

array([[-9, -7, -5, -3, -1],
       [ 1,  3,  5,  7,  9]])

In [13]:
arr1-2

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8]])

In [14]:
arr1-arr3

array([[0, 0, 0, 0, 0],
       [5, 5, 5, 5, 5]])

In [15]:
# division 

In [16]:
arr1/arr2

array([[ 0.1       ,  0.22222222,  0.375     ,  0.57142857,  0.83333333],
       [ 1.2       ,  1.75      ,  2.66666667,  4.5       , 10.        ]])

In [17]:
arr1/arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
arr1/4

array([[0.25, 0.5 , 0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  , 2.25, 2.5 ]])

In [19]:
arr1/arr3

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [6.        , 3.5       , 2.66666667, 2.25      , 2.        ]])

In [20]:
# Exponential

In [21]:
arr1** arr2

array([[    1,   512,  6561, 16384, 15625],
       [ 7776,  2401,   512,    81,    10]])

In [22]:
arr1 ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [23]:
# multiplication 

In [4]:
arr1 * arr2  #this is across product

array([[10, 18, 24, 28, 30],
       [30, 28, 24, 18, 10]])

In [5]:
# dot product 

arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [9]:
arr3=arr2.reshape(5,2)

In [11]:
np.dot(arr1,arr3)

array([[ 70,  55],
       [220, 180]])

In [12]:
np.dot(arr3,arr1)

array([[ 64,  83, 102, 121, 140],
       [ 50,  65,  80,  95, 110],
       [ 36,  47,  58,  69,  80],
       [ 22,  29,  36,  43,  50],
       [  8,  11,  14,  17,  20]])

In [13]:
# dot product second method 

np.matmul(arr1,arr3)

array([[ 70,  55],
       [220, 180]])

# Determinant 

In [17]:
# square matrix -> no. of row is equal to no. of column 
detarray=np.array([[-4,10],[0,5]])   #|det| should be square matrix
                                     
    
#det =(4*5) - (-10*0)=-20

In [18]:
'''[+ - +]
   [- + -]
   [+ - +]'''

'[+ - +]\n   [- + -]\n   [+ - +]'

In [19]:
np.linalg.det(detarray)

-19.999999999999996

In [20]:
detarray=np.array([[-4,10,6],[0,5,7],[-9,6,0]])   

In [21]:
np.linalg.det(detarray)

-192.00000000000017

# Inverse of matrix 

In [23]:
arrinv=np.array([[1,2],[3,4]])

In [24]:
np.linalg.inv(arrinv)

#inverse of matrix = 1/det(matrix)*adjoint of matrix
# adjoint = transpose ( co-facters of the matrix )

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
detmat=np.linalg.det(arrinv)
detmat

-2.0000000000000004

In [26]:
#inverse of matrix 
arrinv/detmat

array([[-0.5, -1. ],
       [-1.5, -2. ]])

# Adjoint of the matrix

In [27]:
# transpose

arrinv.transpose()


array([[1, 3],
       [2, 4]])

In [32]:
# reciprocal

arreci=np.array([[10,20],[30,40]],dtype='float')

In [33]:
np.reciprocal(arreci)

array([[0.1       , 0.05      ],
       [0.03333333, 0.025     ]])

# statistics 

In [ ]:
# distribution ,normal statistics

In [34]:
statarr=np.array([[20,-9,-40],[0,10,-1],[7,6,34]])

max()

In [38]:
np.max(statarr)

34

In [36]:
np.max(statarr,axis=0)

array([20, 10, 34])

In [37]:
np.max(statarr,axis=1)

array([20, 10, 34])

min()

In [39]:
np.min(statarr)

-40

In [41]:
np.min(statarr,axis=0)

array([  0,  -9, -40])

In [42]:
np.min(statarr,axis=1)

array([-40,  -1,   6])

sum()

In [43]:
np.sum(statarr)

27

In [44]:
np.sum(statarr,axis=0)

array([27,  7, -7])

In [45]:
np.sum(statarr,axis=1)

array([-29,   9,  47])

argmax()

In [46]:
np.argmax(statarr)

8

In [47]:
statarr

array([[ 20,  -9, -40],
       [  0,  10,  -1],
       [  7,   6,  34]])

In [49]:
np.argmin(statarr)

2

In [50]:
statarr[1,0]=100
statarr[2,1]=-100

In [51]:
np.argmin(statarr)

7

In [52]:
np.argmax(statarr,axis=0)

array([1, 1, 2], dtype=int64)

In [53]:
np.argmax(statarr,axis=1)

array([0, 0, 2], dtype=int64)

In [54]:
np.argmin(statarr,axis=0)

array([2, 2, 0], dtype=int64)

In [55]:
np.argmin(statarr,axis=1)

array([2, 2, 1], dtype=int64)

around()

In [62]:
arr=np.array([3.501,0.98])

In [64]:
np.around(arr,decimals=1)

array([3.5, 1. ])

In [65]:
np.around(arr,decimals=3)

array([3.501, 0.98 ])

floor & ceil

In [66]:
a=np.array([-1.7,-4,2,4.6,-0.7])

In [67]:
np.floor(a)

array([-2., -4.,  2.,  4., -1.])

In [68]:
np.ceil(a)

array([-1., -4.,  2.,  5., -0.])

copy & view

In [69]:
 x=arr.copy()

In [70]:
x

array([3.501, 0.98 ])

In [71]:
x[0]=10

In [72]:
x

array([10.  ,  0.98])

In [73]:
arr

array([3.501, 0.98 ])

In [74]:
y=arr.view()

In [75]:
y

array([3.501, 0.98 ])

In [76]:
y[0]=10

In [77]:
y

array([10.  ,  0.98])

In [78]:
arr

array([10.  ,  0.98])

Iteration 

In [79]:
for i in arr:
    print(i)

10.0
0.98


In [81]:
for i in arr1:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [82]:
for i in np.nditer(arr1):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [83]:
for i in np.nditer(arr1[1]):
    print(i)

6
7
8
9
10
